### ISSUE TITLE
Colorization only works for D/

### ISSUE THREAD

**Issue by leesei** [uocnb/SublimeText2-Logs#1]
Hi, I've been using this package to view logcat logs, but only the D/ logs have been colorized.
![logcat_higglighting](https://f.cloud.github.com/assets/544400/190575/4298c834-7efc-11e2-99a6-25753a022de3.png)

I would like to contribute to the project but I'm new to packages in ST2.
I've read the source files but could find the colorization rules after the line has been categorized.
Could you give me some pointer to how to add the colorization rules?
Thanks.

**Comment by uocnb** [comment]
Syntax highlighting is defined in *.JSON-tmLanguage files, for logcat it is: logcat.JSON-tmLanguage. After edit you must run a Json to tmLanguage in menu Tool > Build. I was added some regex that recognize and colorize kinds of message like: Error, Debug, Info, Warning but it might be not work well with new version of Sublime caused I'm not have enough time to work with Android then no logcat files here to open :P
